detectors:
  TooManyStatements:
    max_statements: 20

directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false

  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false

  "app/mailers":
    InstanceVariableAssumption:
      enabled: false

  "db/migrate":
    FeatureEnvy:
      enabled: false
    IrresponsibleModule:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
