# yaml-language-server: $schema=https://gh-dash.dev/schema.json
defaults:
  prApproveComment: ""

issuesSections:
  - title: "My Issues"
    filters: "is:open author:@me"
  - title: "Assigned"
    filters: "is:open assignee:@me"
  - title: "Involved"
    filters: "is:open involves:@me -author:@me"
  - title: "Unassigned"
    filters: "is:open no:assignee"

pager:
  diff: diffnav

keybindings:
  prs:
    - key: O
      name: code review
      command: >-
        tmux new-window -c "$(pwd)" -n 'pr {{.PrNumber}}' \
        'nvim -c ":lua vim.schedule(function() vim.cmd([[Octo pr edit {{.PrNumber}}]]) end)"'
    - key: T
      name: action runs
      command: >-
        tmux new-window -c "$(pwd)" -n 'actions {{.PrNumber}}' \
        'gh enhance -R {{.RepoName}} {{.PrNumber}}'

theme:
  colors:
    text:
      primary: "#c6d0f5"
      secondary: "#8caaee"
      inverted: "#11111b"
      faint: "#b5bfe2"
      warning: "#e5c890"
      success: "#a6d189"
      error: "#e78284"
    background:
      selected: "#313244"
    border:
      primary: "#8caaee"
      secondary: "#45475a"
      faint: "#313244"
