tap "cjbassi/gotop"

brew "asdf"
brew "bat"
brew "coreutils"
brew "cowsay"
brew "diff-so-fancy"
brew "fd"
brew "findutils"
brew "fortune"
brew "fzf"
brew "gawk"
brew "git"
brew "glances"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "gnupg"
brew "gotop"
brew "gpg"
brew "grep"
brew "jq"
brew "less"
brew "lesspipe"
brew "mas"
brew "neovim"
brew "pinentry-mac"
brew "posting"
brew "ripgrep"
brew "stow"
brew "thefuck"
brew "tig"
brew "tldr"
brew "tmux"
brew "tree"

cask "alfred"
cask "discord"
cask "flux"
cask "font-monaspace-hf"
cask "ghostty"
cask "keybase"
cask "obsidian"
cask "stay"

mas "Clocker", id: 1056643111
mas "Slack", id: 803453959
mas "Tailscale", id: 1475387142
mas "Xcode", id: 497799835
