tap "cjbassi/gotop"
tap "homebrew/cask-versions"

brew "asdf"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "coreutils"
brew "diff-so-fancy"
brew "fd"
brew "fzf"
brew "git"
brew "gotop"
brew "grep"
brew "httpie"
brew "jq"
brew "lesspipe"
brew "mas"
brew "neovim"
brew "ripgrep"
brew "stow"
brew "thefuck"
brew "tig"
brew "tldr"
brew "tmux"
brew "tree"

cask "1password"
cask "alacritty"
cask "alfred"
cask "docker"
cask "flux"
cask "font-hack-nerd-font"
cask "firefox"
cask "firefox-developer-edition"
cask "keybase"
cask "stay"

mas "Clocker", id: 1056643111
mas "Xcode", id: 497799835
