# Catppuccin Frappe theme, using the Mocha base, surfaces, and overlays
# 0 black -> surface1
# 1 red -> red
# 2 green -> green
# 3 yellow -> peach
# 4 blue -> blue
# 5 magenta -> mauve
# 6 cyan -> sky
# 7 white -> subtext0
palette = 0=#45475a
palette = 1=#e78284
palette = 2=#a6d189
palette = 3=#ef9f76
palette = 4=#8caaee
palette = 5=#ca9ee6
palette = 6=#99d1db
palette = 7=#a5adce

# 8  brightblack -> surface2
# 9  brightred -> maroon
# 10 brightgreen -> teal
# 11 brightyellow -> yellow
# 12 brightblue -> lavender
# 13 brightmagenta -> pink
# 14 brightcyan -> sapphire
# 15 brightwhite -> subtext1
palette = 8=#585b70
palette = 9=#ea999c
palette = 10=#81c8be
palette = 11=#e5c890
palette = 12=#babbf1
palette = 13=#f4b8e4
palette = 14=#85c1dc
palette = 15=#b5bfe2

# base
background = 1e1e2e

# text
foreground = c6d0f5

# rosewater
cursor-color = f2d5cf

# crust
cursor-text = 11111b

# overlay2 20%
selection-background = 353749

# text
selection-foreground = c6d0f5

# surface0
split-divider-color = 313244
