# install tpm and plugins if not already installed
if "test ! -d ~/.tmux/plugins/tpm" \
  "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# plugins
set -g @plugin "tmux-plugins/tpm"
# set -g @plugin "arcticicestudio/nord-tmux"
set -g @plugin "catppuccin/tmux"
set -g @plugin "tmux-plugins/tmux-open"
set -g @plugin "tmux-plugins/tmux-resurrect"

# theme options - use mocha background with frappe flavor
set -g @catppuccin_flavor "frappe"
set -g @thm_bg "#1e1e2e"
set -g @catppuccin_pane_status_enabled "yes"
set -g @catppuccin_pane_border_status "yes"
set -g @catppuccin_window_flags "icon"
set -g @catppuccin_window_status_style "custom"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_left_separator "#[fg=#{@_ctp_status_bg},reverse]#[none]"
set -g @catppuccin_window_middle_separator "#[fg=#{@catppuccin_window_number_color},bg=#{@catppuccin_window_text_color}]"
set -g @catppuccin_window_current_middle_separator "#[fg=#{@catppuccin_window_current_number_color},bg=#{@catppuccin_window_current_text_color}]"
set -g @catppuccin_window_right_separator "#[fg=#{@_ctp_status_bg},reverse]█#[none]"
run "~/.tmux/plugins/tmux/catppuccin.tmux"

# use vi keys for different modes
set -g status-keys vi
setw -g mode-keys vi

# set base index to 1 for windows so it's easier to change quickly
set -g base-index 1
set -g renumber-windows on

# monitor windows for activity
setw -g monitor-activity on

# no delay after hitting escape
set -sg escape-time 0

# misc
set -g history-limit 50000
set -g default-terminal "tmux-256color"
set -g repeat-time 200
set -g focus-events on

# status line settings
set -g display-time 4000
set -g status-left "#[bg=#{@thm_blue},fg=#{@thm_crust} bold] #S #[fg=#{@_ctp_status_bg},reverse]#[none]"
set -g status-left-length 0
set -g status-right "#{?client_prefix,#[fg=#{@thm_red} bold]PREFIX,#{?#{==:#{pane_mode},copy-mode},#[fg=#{@thm_yellow} bold]COPY,#[fg=#{@thm_green} bold]NORMAL}}"
set -g status-right-length 0
set -g window-status-separator ""

# copy buffer <-> clipboard
bind C-c run "tmux save-buffer - | pbcopy"
bind C-v run "pbpaste | tmux load-buffer - ';' paste-buffer -d"

# move windows
bind C-S-Left swap-window -t -1
bind C-S-Right swap-window -t +1

# toggle synchronize-panes
bind ` setw synchronize-panes

# clear screen
bind C-l send-keys \; clear-history

# highlight urls
bind C-u {
  copy-mode
  send-keys -X search-backward "(https?://|git@|git://|ssh://|ftp://|file:///)[[:alnum:]?=%/_.:,;~@!#$&()*+-]*"
}

# run tpm - must be at the bottom
run -b "~/.tmux/plugins/tpm/tpm"
