return {
  {
    "nvim-mini/mini.surround",
    version = false,
    opts = {
      mappings = {
        add = "S",
        delete = "ds",
        replace = "cs",
        find = "Sf",
        find_left = "SF",
        highlight = "Sh",
        suffix_last = "l",
        suffix_next = "n",
      },
    },
    keys = {
      { "S", mode = { "n", "x" },
        desc = "Add surround.",
      },
      { "ds",
        desc = "Delete surround.",
      },
      { "cs",
        desc = "Replace surround.",
      },
      { "Sf",
        desc = "Find surround to the right.",
      },
      { "SF",
        desc = "Find surround to the left.",
      },
      { "Sh",
        desc = "Highlight surround.",
      },
    },
  },
}
